//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL
{
    public partial class Author
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Salutation
        {
            get;
            set;
        }
    
        public virtual string FirstName
        {
            get;
            set;
        }
    
        public virtual string LastName
        {
            get;
            set;
        }
    
        public virtual string MiddleName
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<BookAuthor> bookauthors
        {
            get
            {
                if (_bookauthors == null)
                {
                    var newCollection = new FixupCollection<BookAuthor>();
                    newCollection.CollectionChanged += Fixupbookauthors;
                    _bookauthors = newCollection;
                }
                return _bookauthors;
            }
            set
            {
                if (!ReferenceEquals(_bookauthors, value))
                {
                    var previousValue = _bookauthors as FixupCollection<BookAuthor>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupbookauthors;
                    }
                    _bookauthors = value;
                    var newValue = value as FixupCollection<BookAuthor>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupbookauthors;
                    }
                }
            }
        }
        private ICollection<BookAuthor> _bookauthors;

        #endregion
        #region Association Fixup
    
        private void Fixupbookauthors(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (BookAuthor item in e.NewItems)
                {
                    item.author = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (BookAuthor item in e.OldItems)
                {
                    if (ReferenceEquals(item.author, this))
                    {
                        item.author = null;
                    }
                }
            }
        }

        #endregion
    }
}
