//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL
{
    public partial class author
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string salutation
        {
            get;
            set;
        }
    
        public virtual string first_name
        {
            get;
            set;
        }
    
        public virtual string last_name
        {
            get;
            set;
        }
    
        public virtual string middle_name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<book_author> book_author
        {
            get
            {
                if (_book_author == null)
                {
                    var newCollection = new FixupCollection<book_author>();
                    newCollection.CollectionChanged += Fixupbook_author;
                    _book_author = newCollection;
                }
                return _book_author;
            }
            set
            {
                if (!ReferenceEquals(_book_author, value))
                {
                    var previousValue = _book_author as FixupCollection<book_author>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupbook_author;
                    }
                    _book_author = value;
                    var newValue = value as FixupCollection<book_author>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupbook_author;
                    }
                }
            }
        }
        private ICollection<book_author> _book_author;

        #endregion
        #region Association Fixup
    
        private void Fixupbook_author(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (book_author item in e.NewItems)
                {
                    item.author = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (book_author item in e.OldItems)
                {
                    if (ReferenceEquals(item.author, this))
                    {
                        item.author = null;
                    }
                }
            }
        }

        #endregion
    }
}
