//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL
{
    public partial class book
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string isbn
        {
            get;
            set;
        }
    
        public virtual string title
        {
            get;
            set;
        }
    
        public virtual System.DateTime publication_year
        {
            get;
            set;
        }
    
        public virtual System.DateTime insertion_date
        {
            get;
            set;
        }
    
        public virtual bool available
        {
            get;
            set;
        }
    
        public virtual int publisher_id
        {
            get { return _publisher_id; }
            set
            {
                if (_publisher_id != value)
                {
                    if (publisher != null && publisher.id != value)
                    {
                        publisher = null;
                    }
                    _publisher_id = value;
                }
            }
        }
        private int _publisher_id;
    
        public virtual int department_id
        {
            get { return _department_id; }
            set
            {
                if (_department_id != value)
                {
                    if (department != null && department.id != value)
                    {
                        department = null;
                    }
                    _department_id = value;
                }
            }
        }
        private int _department_id;
    
        public virtual int added_by
        {
            get { return _added_by; }
            set
            {
                if (_added_by != value)
                {
                    if (system_users != null && system_users.id != value)
                    {
                        system_users = null;
                    }
                    _added_by = value;
                }
            }
        }
        private int _added_by;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<book_author> book_author
        {
            get
            {
                if (_book_author == null)
                {
                    var newCollection = new FixupCollection<book_author>();
                    newCollection.CollectionChanged += Fixupbook_author;
                    _book_author = newCollection;
                }
                return _book_author;
            }
            set
            {
                if (!ReferenceEquals(_book_author, value))
                {
                    var previousValue = _book_author as FixupCollection<book_author>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupbook_author;
                    }
                    _book_author = value;
                    var newValue = value as FixupCollection<book_author>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupbook_author;
                    }
                }
            }
        }
        private ICollection<book_author> _book_author;
    
        public virtual department department
        {
            get { return _department; }
            set
            {
                if (!ReferenceEquals(_department, value))
                {
                    var previousValue = _department;
                    _department = value;
                    Fixupdepartment(previousValue);
                }
            }
        }
        private department _department;
    
        public virtual publisher publisher
        {
            get { return _publisher; }
            set
            {
                if (!ReferenceEquals(_publisher, value))
                {
                    var previousValue = _publisher;
                    _publisher = value;
                    Fixuppublisher(previousValue);
                }
            }
        }
        private publisher _publisher;
    
        public virtual system_users system_users
        {
            get { return _system_users; }
            set
            {
                if (!ReferenceEquals(_system_users, value))
                {
                    var previousValue = _system_users;
                    _system_users = value;
                    Fixupsystem_users(previousValue);
                }
            }
        }
        private system_users _system_users;
    
        public virtual ICollection<student_book_loan> student_book_loan
        {
            get
            {
                if (_student_book_loan == null)
                {
                    var newCollection = new FixupCollection<student_book_loan>();
                    newCollection.CollectionChanged += Fixupstudent_book_loan;
                    _student_book_loan = newCollection;
                }
                return _student_book_loan;
            }
            set
            {
                if (!ReferenceEquals(_student_book_loan, value))
                {
                    var previousValue = _student_book_loan as FixupCollection<student_book_loan>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupstudent_book_loan;
                    }
                    _student_book_loan = value;
                    var newValue = value as FixupCollection<student_book_loan>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupstudent_book_loan;
                    }
                }
            }
        }
        private ICollection<student_book_loan> _student_book_loan;

        #endregion
        #region Association Fixup
    
        private void Fixupdepartment(department previousValue)
        {
            if (previousValue != null && previousValue.books.Contains(this))
            {
                previousValue.books.Remove(this);
            }
    
            if (department != null)
            {
                if (!department.books.Contains(this))
                {
                    department.books.Add(this);
                }
                if (department_id != department.id)
                {
                    department_id = department.id;
                }
            }
        }
    
        private void Fixuppublisher(publisher previousValue)
        {
            if (previousValue != null && previousValue.books.Contains(this))
            {
                previousValue.books.Remove(this);
            }
    
            if (publisher != null)
            {
                if (!publisher.books.Contains(this))
                {
                    publisher.books.Add(this);
                }
                if (publisher_id != publisher.id)
                {
                    publisher_id = publisher.id;
                }
            }
        }
    
        private void Fixupsystem_users(system_users previousValue)
        {
            if (previousValue != null && previousValue.books.Contains(this))
            {
                previousValue.books.Remove(this);
            }
    
            if (system_users != null)
            {
                if (!system_users.books.Contains(this))
                {
                    system_users.books.Add(this);
                }
                if (added_by != system_users.id)
                {
                    added_by = system_users.id;
                }
            }
        }
    
        private void Fixupbook_author(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (book_author item in e.NewItems)
                {
                    item.book = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (book_author item in e.OldItems)
                {
                    if (ReferenceEquals(item.book, this))
                    {
                        item.book = null;
                    }
                }
            }
        }
    
        private void Fixupstudent_book_loan(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (student_book_loan item in e.NewItems)
                {
                    item.book = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (student_book_loan item in e.OldItems)
                {
                    if (ReferenceEquals(item.book, this))
                    {
                        item.book = null;
                    }
                }
            }
        }

        #endregion
    }
}
