//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace LibraryManagementSystemDAL
{
    public partial class LMSDataModelEntities : ObjectContext
    {
        public const string ConnectionString = "name=LMSDataModelEntities";
        public const string ContainerName = "LMSDataModelEntities";
    
        #region Constructors
    
        public LMSDataModelEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public LMSDataModelEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public LMSDataModelEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<author> authors
        {
            get { return _authors  ?? (_authors = CreateObjectSet<author>("authors")); }
        }
        private ObjectSet<author> _authors;
    
        public ObjectSet<book_author> book_author
        {
            get { return _book_author  ?? (_book_author = CreateObjectSet<book_author>("book_author")); }
        }
        private ObjectSet<book_author> _book_author;
    
        public ObjectSet<book> books
        {
            get { return _books  ?? (_books = CreateObjectSet<book>("books")); }
        }
        private ObjectSet<book> _books;
    
        public ObjectSet<department> departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<department>("departments")); }
        }
        private ObjectSet<department> _departments;
    
        public ObjectSet<publisher> publishers
        {
            get { return _publishers  ?? (_publishers = CreateObjectSet<publisher>("publishers")); }
        }
        private ObjectSet<publisher> _publishers;
    
        public ObjectSet<sex> sexes
        {
            get { return _sexes  ?? (_sexes = CreateObjectSet<sex>("sexes")); }
        }
        private ObjectSet<sex> _sexes;
    
        public ObjectSet<student_book_loan> student_book_loan
        {
            get { return _student_book_loan  ?? (_student_book_loan = CreateObjectSet<student_book_loan>("student_book_loan")); }
        }
        private ObjectSet<student_book_loan> _student_book_loan;
    
        public ObjectSet<student> students
        {
            get { return _students  ?? (_students = CreateObjectSet<student>("students")); }
        }
        private ObjectSet<student> _students;
    
        public ObjectSet<system_users> system_users
        {
            get { return _system_users  ?? (_system_users = CreateObjectSet<system_users>("system_users")); }
        }
        private ObjectSet<system_users> _system_users;
    
        public ObjectSet<user_role> user_role
        {
            get { return _user_role  ?? (_user_role = CreateObjectSet<user_role>("user_role")); }
        }
        private ObjectSet<user_role> _user_role;

        #endregion
    }
}
