//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace LibraryManagementSystemDAL
{
    public partial class LMSDataModelEntities : ObjectContext
    {
        public const string ConnectionString = "name=LMSDataModelEntities";
        public const string ContainerName = "LMSDataModelEntities";
    
        #region Constructors
    
        public LMSDataModelEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public LMSDataModelEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public LMSDataModelEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Author> Authors
        {
            get { return _authors  ?? (_authors = CreateObjectSet<Author>("Authors")); }
        }
        private ObjectSet<Author> _authors;
    
        public ObjectSet<Book> Books
        {
            get { return _books  ?? (_books = CreateObjectSet<Book>("Books")); }
        }
        private ObjectSet<Book> _books;
    
        public ObjectSet<BookAuthor> BookAuthors
        {
            get { return _bookAuthors  ?? (_bookAuthors = CreateObjectSet<BookAuthor>("BookAuthors")); }
        }
        private ObjectSet<BookAuthor> _bookAuthors;
    
        public ObjectSet<Department> Departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<Department>("Departments")); }
        }
        private ObjectSet<Department> _departments;
    
        public ObjectSet<Publisher> Publishers
        {
            get { return _publishers  ?? (_publishers = CreateObjectSet<Publisher>("Publishers")); }
        }
        private ObjectSet<Publisher> _publishers;
    
        public ObjectSet<Session> Sessions
        {
            get { return _sessions  ?? (_sessions = CreateObjectSet<Session>("Sessions")); }
        }
        private ObjectSet<Session> _sessions;
    
        public ObjectSet<Sex> Sexes
        {
            get { return _sexes  ?? (_sexes = CreateObjectSet<Sex>("Sexes")); }
        }
        private ObjectSet<Sex> _sexes;
    
        public ObjectSet<Student> Students
        {
            get { return _students  ?? (_students = CreateObjectSet<Student>("Students")); }
        }
        private ObjectSet<Student> _students;
    
        public ObjectSet<StudentBookLoan> StudentBookLoans
        {
            get { return _studentBookLoans  ?? (_studentBookLoans = CreateObjectSet<StudentBookLoan>("StudentBookLoans")); }
        }
        private ObjectSet<StudentBookLoan> _studentBookLoans;
    
        public ObjectSet<SystemUser> SystemUsers
        {
            get { return _systemUsers  ?? (_systemUsers = CreateObjectSet<SystemUser>("SystemUsers")); }
        }
        private ObjectSet<SystemUser> _systemUsers;
    
        public ObjectSet<UserRole> UserRoles
        {
            get { return _userRoles  ?? (_userRoles = CreateObjectSet<UserRole>("UserRoles")); }
        }
        private ObjectSet<UserRole> _userRoles;

        #endregion
    }
}
