//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL
{
    public partial class student_book_loan
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual System.DateTime issue_date
        {
            get;
            set;
        }
    
        public virtual System.DateTime due_date
        {
            get;
            set;
        }
    
        public virtual System.DateTime return_date
        {
            get;
            set;
        }
    
        public virtual int issuer
        {
            get { return _issuer; }
            set
            {
                if (_issuer != value)
                {
                    if (system_users != null && system_users.id != value)
                    {
                        system_users = null;
                    }
                    _issuer = value;
                }
            }
        }
        private int _issuer;
    
        public virtual int books_id
        {
            get { return _books_id; }
            set
            {
                if (_books_id != value)
                {
                    if (book != null && book.id != value)
                    {
                        book = null;
                    }
                    _books_id = value;
                }
            }
        }
        private int _books_id;
    
        public virtual int students_reg_no
        {
            get { return _students_reg_no; }
            set
            {
                if (_students_reg_no != value)
                {
                    if (student != null && student.reg_no != value)
                    {
                        student = null;
                    }
                    _students_reg_no = value;
                }
            }
        }
        private int _students_reg_no;

        #endregion
        #region Navigation Properties
    
        public virtual book book
        {
            get { return _book; }
            set
            {
                if (!ReferenceEquals(_book, value))
                {
                    var previousValue = _book;
                    _book = value;
                    Fixupbook(previousValue);
                }
            }
        }
        private book _book;
    
        public virtual student student
        {
            get { return _student; }
            set
            {
                if (!ReferenceEquals(_student, value))
                {
                    var previousValue = _student;
                    _student = value;
                    Fixupstudent(previousValue);
                }
            }
        }
        private student _student;
    
        public virtual system_users system_users
        {
            get { return _system_users; }
            set
            {
                if (!ReferenceEquals(_system_users, value))
                {
                    var previousValue = _system_users;
                    _system_users = value;
                    Fixupsystem_users(previousValue);
                }
            }
        }
        private system_users _system_users;

        #endregion
        #region Association Fixup
    
        private void Fixupbook(book previousValue)
        {
            if (previousValue != null && previousValue.student_book_loan.Contains(this))
            {
                previousValue.student_book_loan.Remove(this);
            }
    
            if (book != null)
            {
                if (!book.student_book_loan.Contains(this))
                {
                    book.student_book_loan.Add(this);
                }
                if (books_id != book.id)
                {
                    books_id = book.id;
                }
            }
        }
    
        private void Fixupstudent(student previousValue)
        {
            if (previousValue != null && previousValue.student_book_loan.Contains(this))
            {
                previousValue.student_book_loan.Remove(this);
            }
    
            if (student != null)
            {
                if (!student.student_book_loan.Contains(this))
                {
                    student.student_book_loan.Add(this);
                }
                if (students_reg_no != student.reg_no)
                {
                    students_reg_no = student.reg_no;
                }
            }
        }
    
        private void Fixupsystem_users(system_users previousValue)
        {
            if (previousValue != null && previousValue.student_book_loan.Contains(this))
            {
                previousValue.student_book_loan.Remove(this);
            }
    
            if (system_users != null)
            {
                if (!system_users.student_book_loan.Contains(this))
                {
                    system_users.student_book_loan.Add(this);
                }
                if (issuer != system_users.id)
                {
                    issuer = system_users.id;
                }
            }
        }

        #endregion
    }
}
