//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL
{
    public partial class system_users
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual string username
        {
            get;
            set;
        }
    
        public virtual string password
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> create_date
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> last_login
        {
            get;
            set;
        }
    
        public virtual int user_role_id
        {
            get { return _user_role_id; }
            set
            {
                if (_user_role_id != value)
                {
                    if (user_role != null && user_role.id != value)
                    {
                        user_role = null;
                    }
                    _user_role_id = value;
                }
            }
        }
        private int _user_role_id;
    
        public virtual int sex_id
        {
            get { return _sex_id; }
            set
            {
                if (_sex_id != value)
                {
                    if (sex != null && sex.id != value)
                    {
                        sex = null;
                    }
                    _sex_id = value;
                }
            }
        }
        private int _sex_id;

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<book> books
        {
            get
            {
                if (_books == null)
                {
                    var newCollection = new FixupCollection<book>();
                    newCollection.CollectionChanged += Fixupbooks;
                    _books = newCollection;
                }
                return _books;
            }
            set
            {
                if (!ReferenceEquals(_books, value))
                {
                    var previousValue = _books as FixupCollection<book>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupbooks;
                    }
                    _books = value;
                    var newValue = value as FixupCollection<book>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupbooks;
                    }
                }
            }
        }
        private ICollection<book> _books;
    
        public virtual sex sex
        {
            get { return _sex; }
            set
            {
                if (!ReferenceEquals(_sex, value))
                {
                    var previousValue = _sex;
                    _sex = value;
                    Fixupsex(previousValue);
                }
            }
        }
        private sex _sex;
    
        public virtual ICollection<student_book_loan> student_book_loan
        {
            get
            {
                if (_student_book_loan == null)
                {
                    var newCollection = new FixupCollection<student_book_loan>();
                    newCollection.CollectionChanged += Fixupstudent_book_loan;
                    _student_book_loan = newCollection;
                }
                return _student_book_loan;
            }
            set
            {
                if (!ReferenceEquals(_student_book_loan, value))
                {
                    var previousValue = _student_book_loan as FixupCollection<student_book_loan>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupstudent_book_loan;
                    }
                    _student_book_loan = value;
                    var newValue = value as FixupCollection<student_book_loan>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupstudent_book_loan;
                    }
                }
            }
        }
        private ICollection<student_book_loan> _student_book_loan;
    
        public virtual user_role user_role
        {
            get { return _user_role; }
            set
            {
                if (!ReferenceEquals(_user_role, value))
                {
                    var previousValue = _user_role;
                    _user_role = value;
                    Fixupuser_role(previousValue);
                }
            }
        }
        private user_role _user_role;

        #endregion
        #region Association Fixup
    
        private void Fixupsex(sex previousValue)
        {
            if (previousValue != null && previousValue.system_users.Contains(this))
            {
                previousValue.system_users.Remove(this);
            }
    
            if (sex != null)
            {
                if (!sex.system_users.Contains(this))
                {
                    sex.system_users.Add(this);
                }
                if (sex_id != sex.id)
                {
                    sex_id = sex.id;
                }
            }
        }
    
        private void Fixupuser_role(user_role previousValue)
        {
            if (previousValue != null && previousValue.system_users.Contains(this))
            {
                previousValue.system_users.Remove(this);
            }
    
            if (user_role != null)
            {
                if (!user_role.system_users.Contains(this))
                {
                    user_role.system_users.Add(this);
                }
                if (user_role_id != user_role.id)
                {
                    user_role_id = user_role.id;
                }
            }
        }
    
        private void Fixupbooks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (book item in e.NewItems)
                {
                    item.system_users = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (book item in e.OldItems)
                {
                    if (ReferenceEquals(item.system_users, this))
                    {
                        item.system_users = null;
                    }
                }
            }
        }
    
        private void Fixupstudent_book_loan(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (student_book_loan item in e.NewItems)
                {
                    item.system_users = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (student_book_loan item in e.OldItems)
                {
                    if (ReferenceEquals(item.system_users, this))
                    {
                        item.system_users = null;
                    }
                }
            }
        }

        #endregion
    }
}
