//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL.Data
{
    public partial class Department
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Name
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<Book> books
        {
            get
            {
                if (_books == null)
                {
                    var newCollection = new FixupCollection<Book>();
                    newCollection.CollectionChanged += Fixupbooks;
                    _books = newCollection;
                }
                return _books;
            }
            set
            {
                if (!ReferenceEquals(_books, value))
                {
                    var previousValue = _books as FixupCollection<Book>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupbooks;
                    }
                    _books = value;
                    var newValue = value as FixupCollection<Book>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupbooks;
                    }
                }
            }
        }
        private ICollection<Book> _books;
    
        public virtual ICollection<Student> students
        {
            get
            {
                if (_students == null)
                {
                    var newCollection = new FixupCollection<Student>();
                    newCollection.CollectionChanged += Fixupstudents;
                    _students = newCollection;
                }
                return _students;
            }
            set
            {
                if (!ReferenceEquals(_students, value))
                {
                    var previousValue = _students as FixupCollection<Student>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupstudents;
                    }
                    _students = value;
                    var newValue = value as FixupCollection<Student>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupstudents;
                    }
                }
            }
        }
        private ICollection<Student> _students;

        #endregion
        #region Association Fixup
    
        private void Fixupbooks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Book item in e.NewItems)
                {
                    item.department = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Book item in e.OldItems)
                {
                    if (ReferenceEquals(item.department, this))
                    {
                        item.department = null;
                    }
                }
            }
        }
    
        private void Fixupstudents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Student item in e.NewItems)
                {
                    item.department = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Student item in e.OldItems)
                {
                    if (ReferenceEquals(item.department, this))
                    {
                        item.department = null;
                    }
                }
            }
        }

        #endregion
    }
}
