//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;

namespace LibraryManagementSystemDAL.Data
{
    public partial class LMSDataModelEntities : ObjectContext
    {
        public const string ConnectionString = "name=LMSDataModelEntities";
        public const string ContainerName = "LMSDataModelEntities";
    
        #region Constructors
    
        public LMSDataModelEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public LMSDataModelEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        public LMSDataModelEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
    		this.ContextOptions.ProxyCreationEnabled = false;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<author> authors
        {
            get { return _authors  ?? (_authors = CreateObjectSet<author>("authors")); }
        }
        private ObjectSet<author> _authors;
    
        public ObjectSet<book> books
        {
            get { return _books  ?? (_books = CreateObjectSet<book>("books")); }
        }
        private ObjectSet<book> _books;
    
        public ObjectSet<bookauthor> bookauthors
        {
            get { return _bookauthors  ?? (_bookauthors = CreateObjectSet<bookauthor>("bookauthors")); }
        }
        private ObjectSet<bookauthor> _bookauthors;
    
        public ObjectSet<department> departments
        {
            get { return _departments  ?? (_departments = CreateObjectSet<department>("departments")); }
        }
        private ObjectSet<department> _departments;
    
        public ObjectSet<publisher> publishers
        {
            get { return _publishers  ?? (_publishers = CreateObjectSet<publisher>("publishers")); }
        }
        private ObjectSet<publisher> _publishers;
    
        public ObjectSet<session> sessions
        {
            get { return _sessions  ?? (_sessions = CreateObjectSet<session>("sessions")); }
        }
        private ObjectSet<session> _sessions;
    
        public ObjectSet<sex> sexes
        {
            get { return _sexes  ?? (_sexes = CreateObjectSet<sex>("sexes")); }
        }
        private ObjectSet<sex> _sexes;
    
        public ObjectSet<student> students
        {
            get { return _students  ?? (_students = CreateObjectSet<student>("students")); }
        }
        private ObjectSet<student> _students;
    
        public ObjectSet<studentbookloan> studentbookloans
        {
            get { return _studentbookloans  ?? (_studentbookloans = CreateObjectSet<studentbookloan>("studentbookloans")); }
        }
        private ObjectSet<studentbookloan> _studentbookloans;
    
        public ObjectSet<systemuser> systemusers
        {
            get { return _systemusers  ?? (_systemusers = CreateObjectSet<systemuser>("systemusers")); }
        }
        private ObjectSet<systemuser> _systemusers;
    
        public ObjectSet<userrole> userroles
        {
            get { return _userroles  ?? (_userroles = CreateObjectSet<userrole>("userroles")); }
        }
        private ObjectSet<userrole> _userroles;

        #endregion
    }
}
