//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL.Data
{
    public partial class Session
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual System.DateTime CreationDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime ExpirationDate
        {
            get;
            set;
        }
    
        public virtual Nullable<System.DateTime> LastAccessDate
        {
            get;
            set;
        }
    
        public virtual int SystemUser_id
        {
            get { return _systemUser_id; }
            set
            {
                if (_systemUser_id != value)
                {
                    if (systemuser != null && systemuser.Id != value)
                    {
                        systemuser = null;
                    }
                    _systemUser_id = value;
                }
            }
        }
        private int _systemUser_id;

        #endregion
        #region Navigation Properties
    
        public virtual SystemUser systemuser
        {
            get { return _systemuser; }
            set
            {
                if (!ReferenceEquals(_systemuser, value))
                {
                    var previousValue = _systemuser;
                    _systemuser = value;
                    Fixupsystemuser(previousValue);
                }
            }
        }
        private SystemUser _systemuser;

        #endregion
        #region Association Fixup
    
        private void Fixupsystemuser(SystemUser previousValue)
        {
            if (previousValue != null && previousValue.sessions.Contains(this))
            {
                previousValue.sessions.Remove(this);
            }
    
            if (systemuser != null)
            {
                if (!systemuser.sessions.Contains(this))
                {
                    systemuser.sessions.Add(this);
                }
                if (SystemUser_id != systemuser.Id)
                {
                    SystemUser_id = systemuser.Id;
                }
            }
        }

        #endregion
    }
}
