//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL.Data
{
    public partial class sex
    {
        #region Primitive Properties
    
        public virtual int Id
        {
            get;
            set;
        }
    
        public virtual string Description
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ICollection<student> students
        {
            get
            {
                if (_students == null)
                {
                    var newCollection = new FixupCollection<student>();
                    newCollection.CollectionChanged += Fixupstudents;
                    _students = newCollection;
                }
                return _students;
            }
            set
            {
                if (!ReferenceEquals(_students, value))
                {
                    var previousValue = _students as FixupCollection<student>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupstudents;
                    }
                    _students = value;
                    var newValue = value as FixupCollection<student>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupstudents;
                    }
                }
            }
        }
        private ICollection<student> _students;
    
        public virtual ICollection<systemuser> systemusers
        {
            get
            {
                if (_systemusers == null)
                {
                    var newCollection = new FixupCollection<systemuser>();
                    newCollection.CollectionChanged += Fixupsystemusers;
                    _systemusers = newCollection;
                }
                return _systemusers;
            }
            set
            {
                if (!ReferenceEquals(_systemusers, value))
                {
                    var previousValue = _systemusers as FixupCollection<systemuser>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= Fixupsystemusers;
                    }
                    _systemusers = value;
                    var newValue = value as FixupCollection<systemuser>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += Fixupsystemusers;
                    }
                }
            }
        }
        private ICollection<systemuser> _systemusers;

        #endregion
        #region Association Fixup
    
        private void Fixupstudents(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (student item in e.NewItems)
                {
                    item.sex = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (student item in e.OldItems)
                {
                    if (ReferenceEquals(item.sex, this))
                    {
                        item.sex = null;
                    }
                }
            }
        }
    
        private void Fixupsystemusers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (systemuser item in e.NewItems)
                {
                    item.sex = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (systemuser item in e.OldItems)
                {
                    if (ReferenceEquals(item.sex, this))
                    {
                        item.sex = null;
                    }
                }
            }
        }

        #endregion
    }
}
