//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace LibraryManagementSystemDAL.Data
{
    public partial class studentbookloan
    {
        #region Primitive Properties
    
        public virtual int id
        {
            get;
            set;
        }
    
        public virtual System.DateTime IssueDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime DueDate
        {
            get;
            set;
        }
    
        public virtual System.DateTime ReturnDate
        {
            get;
            set;
        }
    
        public virtual int IssuerID
        {
            get { return _issuerID; }
            set
            {
                if (_issuerID != value)
                {
                    if (systemuser != null && systemuser.Id != value)
                    {
                        systemuser = null;
                    }
                    _issuerID = value;
                }
            }
        }
        private int _issuerID;
    
        public virtual int StudentID
        {
            get { return _studentID; }
            set
            {
                if (_studentID != value)
                {
                    if (student != null && student.Id != value)
                    {
                        student = null;
                    }
                    _studentID = value;
                }
            }
        }
        private int _studentID;
    
        public virtual int BookId
        {
            get { return _bookId; }
            set
            {
                if (_bookId != value)
                {
                    if (book != null && book.Id != value)
                    {
                        book = null;
                    }
                    _bookId = value;
                }
            }
        }
        private int _bookId;

        #endregion
        #region Navigation Properties
    
        public virtual book book
        {
            get { return _book; }
            set
            {
                if (!ReferenceEquals(_book, value))
                {
                    var previousValue = _book;
                    _book = value;
                    Fixupbook(previousValue);
                }
            }
        }
        private book _book;
    
        public virtual student student
        {
            get { return _student; }
            set
            {
                if (!ReferenceEquals(_student, value))
                {
                    var previousValue = _student;
                    _student = value;
                    Fixupstudent(previousValue);
                }
            }
        }
        private student _student;
    
        public virtual systemuser systemuser
        {
            get { return _systemuser; }
            set
            {
                if (!ReferenceEquals(_systemuser, value))
                {
                    var previousValue = _systemuser;
                    _systemuser = value;
                    Fixupsystemuser(previousValue);
                }
            }
        }
        private systemuser _systemuser;

        #endregion
        #region Association Fixup
    
        private void Fixupbook(book previousValue)
        {
            if (previousValue != null && previousValue.studentbookloans.Contains(this))
            {
                previousValue.studentbookloans.Remove(this);
            }
    
            if (book != null)
            {
                if (!book.studentbookloans.Contains(this))
                {
                    book.studentbookloans.Add(this);
                }
                if (BookId != book.Id)
                {
                    BookId = book.Id;
                }
            }
        }
    
        private void Fixupstudent(student previousValue)
        {
            if (previousValue != null && previousValue.studentbookloans.Contains(this))
            {
                previousValue.studentbookloans.Remove(this);
            }
    
            if (student != null)
            {
                if (!student.studentbookloans.Contains(this))
                {
                    student.studentbookloans.Add(this);
                }
                if (StudentID != student.Id)
                {
                    StudentID = student.Id;
                }
            }
        }
    
        private void Fixupsystemuser(systemuser previousValue)
        {
            if (previousValue != null && previousValue.studentbookloans.Contains(this))
            {
                previousValue.studentbookloans.Remove(this);
            }
    
            if (systemuser != null)
            {
                if (!systemuser.studentbookloans.Contains(this))
                {
                    systemuser.studentbookloans.Add(this);
                }
                if (IssuerID != systemuser.Id)
                {
                    IssuerID = systemuser.Id;
                }
            }
        }

        #endregion
    }
}
